AMINO_ACIDS = "ARNDCQEGHILKMFPSTWYV"


def amino_acid_sequence_check(
    sequence: str, allow_unknown: bool = False, allow_stop: bool = False
) -> bool:
    """
    Checks if a sequence is a valid amino acid sequence (only contains valid amino acids
    characters and optionally unknown and stop characters)

    Args:
        sequence: The sequence to check.
        allow_unknown: Whether to allow unknown amino acids.
        allow_stop: Whether to allow stop codons.

    Returns:
        True if the sequence is a valid amino acid sequence, False otherwise.
    """

    AMINO_ACIDS_SET = set(AMINO_ACIDS)

    # If we are allowing unknown amino acids, add to the set
    if allow_unknown:
        AMINO_ACIDS_SET.add("X")  # X is standard unknown amino acid

    # If we are allowing stop codons, add to the set
    if allow_stop:
        AMINO_ACIDS_SET.add("*")

    return set(sequence).issubset(AMINO_ACIDS_SET)


# EXAMPLE SEQUENCES
GFP = "MSKGEELFTGVVPILVELDGDVNGHKFSVSGEGEGDATYGKLTLKFICTTGKLPVPWPTLVTTFSYGVQCFSRYPDHMKQHDFFKSAMPEGYVQERTIFFKDDGNYKTRAEVKFEGDTLVNRIELKGIDFKEDGNILGHKLEYNYNSHNVYIMADKQKNGIKVNFKIRHNIEDGSVQLADHYQQNTPIGDGPVLLPDNHYLSTQSALSKDPNEKRDHMVLLEFVTAAGITHGMDELYK"
AAV_WT_VP3 = "MATGSGAPMADNNEGADGVGNSSGNWHCDSTWMGDRVITTSTRTWALPTYNNHLYKQISSQSGASNDNHYFGYSTPWGYFDFNRFHCHFSPRDWQRLINNNWGFRPKRLNFKLFNIQVKEVTQNDGTTTIANNLTSTVQVFTDSEYQLPYVLGSAHQGCLPPFPADVFMVPQYGYLTLNNGSQAVGRSSFYCLEYFPSQMLRTGNNFTFSYTFEDVPFHSSYAHSQSLDRLMNPLIDQYLYYLSRTNTPSGTTTQSRLQFSQAGASDIRDQSRNWLPGPCYRQQRVSKTSADNNNSEYSWTGATKYHLNGRDSLVNPGPAMASHKDDEEKFFPQSGVLIFGKQGSEKTNVDIEKVMITDEEEIRTTNPVATEQYGSVSTNLQRGNRQAATADVNTQGVLPGMVWQDRDVYLQGPIWAKIPHTDGHFHPSPLMGGFGLKHPPPQILIKNTPVPANPSTTFSAAKFASFITQYSTGQVSVEIEWELQKENSKRWNPEIQYTSNYNKSVNVDFTVDTNGVYSEPRPIGTRYLTRNL"
