# .github/workflows/test-install.yml
name: Test PyProject Install

on:
  pull_request:
    branches: [main]

jobs:
  test-install:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.11]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Upgrade pip and build tools
        run: |
          python -m pip install --upgrade pip
          pip install build

      - name: Install package via pip (pyproject.toml)
        run: |
          pip install uv
          uv pip install . --system

      - name: Verify package import
        run: |
          python -c "import provada"
